# This file lists the types of unlocks. 
# All times unless otherwise
# specified as seconds are given in the following format: 
# 12w3d4h5m6s , which is 12 weeks, 3 days, 4 hours, 5 minutes,
# 6 seconds

warning_beeps_time: [
  "10m", .5, #.5 seconds beep at 10 minutes
  "5m", .5, .5, .5, #.5s beep, .5 off, .5 beep at 5 minutes
  "1m", 1, .5, 1, .5, 1,
  "30s", 1, .5, 1, .5, 1, .5, 1
]

grace_period_seconds: 90
grace_period_exceeded_callback: "unlock_grace_period_exceeded"
orgasm_penalty_callback: "unlock_orgasmed_unauthorized_callback"


unlock_default_callbacks:
  wearer_init_callback: "unlock_default"
  kh_init_callback: "unlock_default"
  wearer_request_callback: "unlock_request_default"
  orgasm_penalty_callback: "unlock_orgasmed_unauthorized"
  allowance_callback: "unlock_default_allowance"
  

default_unlock_template:
  display_name: ""
  enabled: true
  wearer_can_init: true
  wearer_can_request: true
  wearer_init_delay_seconds: 0
  disabled_by_notouch: true
  allowance:
    enabled: true
    increment_every: "24h"
    increment_by: "30m"

unlocks:
  cleaning:
    display_name: "Cleaning"
    wearer_can_init: true
    wearer_can_request: true
  dilation:
    display_name: "Dilation"
    wearer_can_init: true
    wearer_can_request: true
    disabled_by_notouch: false
  play:
    display_name: "Play"
    enabled: true
    wearer_can_init: true
    wearer_can_request: true
    disabled_by_notouch: true
  release:
    display_name: "Release"
    enabled: true
    wearer_can_init: true
    wearer_can_request: true
    disabled_by_notouch: true
  break:
    display_name : "Break"
    wearer_can_init: false
    wearer_can_request: true
  #I strongly recommend that Emergency not be disabled without a
  #backup emergency plan, such as a key in a sealed envelope.
  emergency:
    display_name: "Emergency"
    wearer_init_delay_seconds: 300 
    wearer_can_init: true
    wearer_can_request: true

