# This defines usernames and passwords.
# TODO how to generate a password

#If salt is set to CHANGE, on next run CBSafe will
#assign a random salt.
salt: "CHANGE" 
session_length_seconds : 36000

users:
  alice: #username
    display_name: "Pet Alice"
    passwd: ""
    #If passwd_clear is set, on next run, CBSafe will delete this 
    # field and fill out passwd with the encrypted version.
    passwd_clear : "password" 
    access_type: "wearer"
    # Valid access types include:
    # - wearer
    # - wearer,admin
    # - keyholder
    # - keyholder,admin
    # See the documentation for the differences.
  barbara: 
    display_name: "Mistress Barbara"
    passwd: ""
    passwd_clear: "password"
    access_type: "keyholder"

bots:
  botty: #bots name
    token: "" #mandatory access token
    display_name: "Botty the KH Bot" #optional display name
    access_type: "keyholder" #determines if bot is treated with admin
    enabled: true

anonymous:
  show_status: false
