# Autogenerated file
def render(lockstatus):
    yield """<!DOCTYPE html>
<html lang=\"en\">
<head>
    <title>CBSafe</title>
</head>
<body>
    <div>
        <a href=\"about\">About</a>
        <a href=\"rules\">Rules</a>
        <a href=\"games\">Games</a>
        <a href=\"journal\">Journal</a>
        <a href=\"settings\">Settings</a>
        <a href=\"help\">Help</a>
        <a href=\"logout\">Logout (%USER.NAME%)</a>
    </div>
    <h1>CBSafe</h1>

    <h2>Status</h2>
    <p><b>"""
    yield """{ """
